name: Test Trigger

on:
  schedule:
    - cron: '55 13 * * 3'

jobs:
  trigger-test:
    runs-on: ubuntu-latest

    steps:
    - name: Set environment and trigger test
      run: |
          echo "Setting environment as testing and trigger type as scheduled"
          echo "environment=testing" >> $GITHUB_ENV
          echo "trigger_type=scheduled" >> $GITHUB_ENV

    - name: Trigger experiment workflow
      run: |
          echo "Triggering experiment workflow with environment=${{ env.environment }} and trigger_type=${{ env.trigger_type }}"
          # You can trigger your common experiment workflow manually by using curl or other methods if needed.
